# Generated by Django 4.0.1 on 2022-01-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('due_date', models.DateField(default=None)),
                ('time', models.CharField(default=None, max_length=5)),
                ('am_pm', models.CharField(default=None, max_length=2)),
            ],
        ),
    ]
