# Generated by Django 4.0.1 on 2022-01-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('due_date', models.DateField(default=None)),
                ('time', models.CharField(choices=[('12:00', '12:00'), ('12:30', '12:30'), ('1:00', '1:00'), ('1:30', '1:30'), ('2:00', '2:00'), ('2:30', '2:30'), ('3:00', '3:00'), ('3:30', '3:30'), ('4:00', '4:00'), ('4:30', '4:30'), ('5:00', '5:00'), ('5:30', '5:30'), ('6:00', '6:00'), ('6:30', '6:30'), ('7:00', '7:00'), ('7:30', '7:30'), ('8:00', '8:00'), ('8:30', '8:30'), ('9:00', '9:00'), ('9:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30')], default=None, max_length=5)),
                ('am_pm', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default=None, max_length=2)),
            ],
        ),
    ]
